project:
  type: website
  output-dir: docs
website:
  title: "CrystalNodes"
  navbar:
    left:
      - href: index.qmd
        text: Home
     
  sidebar:
    style: "docked"
    search: true
    collapse-level: 6
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - install.qmd
      - section: "Nodes"
        contents:
          - section: "Forms"
            contents:
            - iso.qmd
            - Non-iso.qmd
          - section: "Tools"
            contents:
            - tools.qmd 
format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

