project:
  type: website
  output-dir: docs
website:
  title: "CrystalNodes"
  navbar:
    left:
      - href: index.qmd
        text: Home
     
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - install.qmd
          
      - section: "Nodes"
        contents:
         
          - tools.qmd
          - primitives.qmd
          - growth pattern.qmd
format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

